from typing import Any, Protocol
from uuid import UUID

from src.domain.models.entities import (
    Agent,
    Claim,
    ClaimKind,
    CreditNote,
    Document,
    GroupClaim,
    Invoice,
    Payment,
    PaymentVia,
    Period,
    SosClaim,
    User,
)

##Protocolos Base######################################################################


class BaseRepo[T](Protocol):
    def add(self, model: T): ...

    def get_by_id(self, id: UUID) -> T | None: ...

    def delete(self, id: UUID): ...

    def update(self, id: UUID, model: T) -> bool: ...

    def get_all(self) -> list[T]: ...

    def exists(self, data: dict[str, Any]) -> bool: ...

    def get_by_ids(self, ids: list[UUID]) -> list[T]: ...


class _Activatable[T](Protocol):
    def activate(self, id: UUID) -> bool: ...
    def inactivate(self, id: UUID) -> bool: ...


class _DocReachable[T](Protocol):
    def get_by_document_id(self, document_id: UUID) -> list[T]: ...
    def get_by_document(self, document: bytes) -> list[T]: ...


##Protocolos de Repositorio######################################################################


class UserRepoPort(BaseRepo[User], _Activatable[User], Protocol):
    def get_by_email(self, email: str) -> User | None: ...
    def get_by_name(self, name: str) -> User | None: ...
    def add_user(self, user_name: str, email: str, password_hash: str) -> User: ...


class PeriodRepoPort(BaseRepo[Period], _Activatable[Period], Protocol):
    def get_by_year_month(self, year: int, month: int) -> Period | None: ...
    def get_n_last(self, n: int | None) -> list[Period]: ...
    def get_total_billing_by_year_month(self, year: int, month: int) -> float: ...


class BillingRepoPort(BaseRepo[Invoice], _DocReachable[Invoice], Protocol): ...


class AgentRepoPort(BaseRepo[Agent], _Activatable[Agent], Protocol):
    def get_by_name(self, name: str) -> Agent | None: ...
    def get_sm(self) -> Agent | None: ...
    def get_prestador(self) -> Agent | None: ...
    def get_sos(self) -> Agent | None: ...
    def get_asegurado(self) -> Agent | None: ...


class PaymentViaRepoPort(BaseRepo[PaymentVia], _Activatable[PaymentVia], Protocol):
    def get_by_name(self, name: str) -> PaymentVia | None: ...
    def get_transferencia(self) -> PaymentVia | None: ...
    def get_nc(self) -> PaymentVia | None: ...


class ClaimKindRepoPort(BaseRepo[ClaimKind], _Activatable[ClaimKind], Protocol):
    def get_by_name(self, name: str) -> ClaimKind | None: ...


class ClaimRepoPort(BaseRepo[Claim], _DocReachable[Claim], _Activatable[Claim], Protocol):
    def get_by_text_like(self, text: str) -> Claim | None: ...


class SosClaimRepoPort(BaseRepo[SosClaim], _Activatable[SosClaim], Protocol):
    def get_claims_by_claim_id(self, claim_id: UUID) -> list[SosClaim]: ...
    def get_by_number(self, claim_number: int) -> SosClaim | None: ...
    def get_by_status(self, status: str) -> list[SosClaim]: ...
    def get_by_text_like(self, text: str) -> SosClaim | None: ...


class GroupClaimRepoPort(BaseRepo[GroupClaim], _DocReachable[GroupClaim], Protocol):
    def get_by_claim_id(self, claim_id: UUID) -> GroupClaim: ...
    def get_by_group_name(self, group_name: str) -> GroupClaim: ...
    def get_by_text_like(self, text: str) -> list[GroupClaim]: ...


class PaymentRepoPort(BaseRepo[Payment], Protocol):
    def deleteable(self, id: UUID) -> bool: ...
    def get_by_claim_id(self, claim_id: UUID) -> list[Payment]: ...
    def get_by_date_range(self, start_date: str, end_date: str) -> list[Payment]: ...
    def get_by_amount_range(self, min_amount: float, max_amount: float) -> list[Payment]: ...


class NcPaymentRepoPort(BaseRepo[CreditNote], Protocol):
    def deleteable(self, id: UUID) -> bool: ...
    def get_by_payment_id(self, payment_id: UUID) -> CreditNote | None: ...
    def get_by_period_id(self, period_id: UUID) -> list[CreditNote]: ...


class DocumentRepoPort(BaseRepo[Document], Protocol):
    def get_by_content(self, content: bytes) -> Document | None: ...
    def get_by_name(self, name: str) -> Document | None: ...
    def get_by_claim_id(self, claim_id: UUID) -> list[Document]: ...
    def get_by_group_id(self, group_id: UUID) -> list[Document]: ...
    def get_by_billing_id(self, billing_id: UUID) -> Document | None: ...
