services:
  db:
    image: postgres:16-alpine
    container_name: gestiones_sos_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: gestiones_sos
      POSTGRES_USER: sos_user
      POSTGRES_PASSWORD: sos_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
