"""make group_id nullable on claims

Revision ID: bf72ed01b026
Revises: 0d1e2f3a4b5c
Create Date: 2026-06-24 22:43:10.915631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf72ed01b026'
down_revision: Union[str, Sequence[str], None] = '0d1e2f3a4b5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'audit_log', 'users', ['performed_by'], ['user_id'])
    op.alter_column('claims', 'group_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('claims', 'group_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'audit_log', type_='foreignkey')
    # ### end Alembic commands ###
