from typing import Any, Protocol
from uuid import UUID

from src.domain.models.entities import User


class UserRepository(Protocol):
    def add(self, model: User) -> User: ...

    def get_by_id(self, id: UUID) -> User | None: ...

    def delete(self, id: UUID) -> None: ...

    def update(self, id: UUID, model: User) -> bool: ...

    def get_all(self) -> list[User]: ...

    def exists(self, data: dict[str, Any]) -> bool: ...

    def get_by_ids(self, ids: list[UUID]) -> list[User]: ...

    def get_by_email(self, email: str) -> User | None: ...

    def get_by_name(self, name: str) -> User | None: ...

    def add_user(self, user_name: str, email: str, password_hash: str) -> User: ...

    def activate(self, id: UUID) -> bool: ...

    def inactivate(self, id: UUID) -> bool: ...
